name: "Terraform CICD"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      aws-assume-role:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      aws-statefile-s3-bucket:
        required: true
        type: string
      aws-statefile-dynamodb-table:
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    
    steps:
        - name: Checkout code
          uses: actions/checkout@v4 #actions do próprio GitHub
        
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3 #actions do próprio GitHub
          with:
            terraform_version: 1.8.3
        
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4 #actions do próprio GitHub
          with:
            role-to-assume: ${{ inputs.aws-assume-role }}
            role-session-name: github-actions-terraform
            aws-region: ${{ inputs.aws-region }}
        
        - name: Read destroy configuration
          id: read-destroy-config
          run: |
            DESTROY_CONFIG="$(jq -r '.${{ inputs.environment }}' ./infra/destroy_config.json)""
            echo "destroy=$(echo $DESTROY_CONFIG)" >> $GITHUB_OUTPUT

        - name: Terraform Init
          run: |
            cd infra && terraform init \
              -backend-config="bucket=${{ inputs.aws-statefile-s3-bucket }}" \
              -backend-config="key=${{ github.event.repository.name }}/${{ inputs.environment }}.tfstate" \
              -backend-config="region=${{ inputs.aws-region }}" \
              -backend-config="dynamodb_table=${{ inputs.aws-statefile-dynamodb-table }}"
       
        - name: Terraform Validate
          id: terraform-validate
          run: |
            cd infra && terraform validate

        - name: Terraform Destroy
          if: steps.read-destroy-config.outputs.destroy == 'true'
          id: terraform-destroy
          run: |
            cd infra && \
            terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} && \
            terraform destroy -auto-approve -var-file="./envs/${{ inputs.environment }}/terraform.tfvars"

        - name: Terraform Plan
          if: steps.read-destroy-config.outputs.destroy != 'true'
          id: terraform-plan
          run: |
            cd infra && \
            terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} && \
            terraform plan -input=false -var-file="./envs/${{ inputs.environment }}/terraform.tfvars" -out="${{ inputs.environment }}.plan"

        - name: Terraform Apply
          if: steps.read-destroy-config.outputs.destroy != 'true'
          id: terraform-apply
          run: |
            cd infra && \
            terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} && \
            terraform apply -input=false "${{ inputs.environment }}.plan"